# For Github User
# github_username: "slack_member_id"

ogiyasu: 'U2GCTPG5S'
tamaitomoaki: 'U51QZQFV0'
kyonallafesta: 'U2GDL8WUS'
Taishi-Suzuki: 'U12F6UMFF'
jshimazu: 'U01645J5V52'
github_username_C: 'slack_member_id_C'
abeyuya: 'XXXXXXXXX'

# For Github Team
# github_teamname: "slack_member_id"

github_teamname_A: 'slack_member_id_D'
