name: "units-test"
on:
  issues:
    types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Assign to issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: run assignToIssue action
        uses: ./.github/actions/assignToIssue # Uses an action in the root directory
        id: assignToIssue
      - name: notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.TEST }}
        with:
          text: Successfully automated deployment.
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "issueにアサインされました。"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.assignToIssue.outputs.mention }} ご確認お願いいたします。"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>"
                }
              },
            ]
