name: "units-test"
on:
  issues:
    types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: https://hooks.slack.com/services/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
        with:
          text: Hello, Slack!
