name: "units-test"
on:
  pull_request:
    types: [labeled]
  # issues:
  #   types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: https://hooks.slack.com/services/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
        with:
          text: Hello, Slack!
