name: "units-test"
on:
  issues:
    types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: https://hooks.slack.com/services/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
        with:
          text: Successfully automated deployment.
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "issueにアサインされました。ご確認お願いいたします。"
                }
              },
              {
                "type": "divider"
              },
            ]
