name: "units-test"
on:
  issues:
    types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - run: git status
      - run: git branch
      - run: pwd
      - run: ls -la
